service: optimized-aws-sdk-function

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
    layers:
      - arn:aws:lambda:us-east-1:374852340823:layer:optimized-aws-sdk:1